; -------------------------------------------------------------------------
; Sonic CD Disassembly
; By Ralakimus 2021
; -------------------------------------------------------------------------
; Wacky Workbench Act 1 Present
; -------------------------------------------------------------------------

	include	"Level/_Definitions.i"

; -------------------------------------------------------------------------

	include	"Level/Initialization.asm"
	include	"Level/Wacky Workbench/Palette Cycle (Present).asm"
	include	"Level/Palette Fade.asm"
	include	"Level/Palette Load (Fade).asm"
	include	"Level/Palette Load.asm"
	include	"Level/Palette Load (Water).asm"
	include	"Level/Palette Load (Water Fade).asm"
	include	"Level/Wacky Workbench/Palette Data (Act 1 Present).asm"
	include	"Level/Functions (Misc).asm"
	include	"Level/Collision Floor.asm"
	include	"Level/Main.asm"
	include	"Level/Functions (General).asm"
	include	"Level/Wacky Workbench/Scroll (Act 1 Present).asm"
	include	"Level/Wacky Workbench/Load Level Data.asm"
	include	"Level/_Events.asm"
	include	"Level/Object Functions.asm"
	include	"Level/Wacky Workbench/Object Index (Act 1 Present).asm"
	include	"Level/Wacky Workbench/Objects/Sonic/Main.asm"
	include	"Level/Sub CPU.asm"
	include	"Level/Object Animate.asm"
	include	"Level/_Objects/Checkpoint/Main.asm"
	include	"Level/Resume Music (Leftover).asm"
	include	"Level/_Objects/Test Badnik/Main.asm"
	include	"Level/_Objects/Explosion/Main.asm"
	include	"Level/_Objects/Flower/Main.asm"
	include	"Level/_Objects/Spin Tunnel/Main (Waterfall Splash).asm"
	include	"Level/_Objects/Spin Tunnel/Main (Door).asm"
	include	"Level/_Objects/Powerup/Main.asm"
	include	"Level/_Objects/Spin Tunnel/Main (Tag).asm"
	include	"Level/Load Saved Data.asm"
	include	"Level/Collision Check.asm"
	include	"Level/Wacky Workbench/Player Object Collision.asm"
	include	"Level/Debug Mode.asm"
	include	"Level/Wacky Workbench/Debug Objects (Act 1 Present).asm"
	include	"Level/Object Spawner.asm"
	include	"Level/Wacky Workbench/Object Layout (Act 1).asm"
	include	"Level/Wacky Workbench/Objects/Goddess Statue/Main.asm"
	include	"Level/Wacky Workbench/Objects/Freezer/Main.asm"
	include	"Level/Wacky Workbench/Objects/Launcher/Main.asm"
	include	"Level/Wacky Workbench/Objects/Tunnel Path/Main.asm"
	include	"Level/Object Solid.asm"
	include	"Level/_Objects/Boulder/Main.asm"
	include	"Level/_Objects/Spring/Main.asm"
	include	"Level/_Objects/Ring/Main.asm"
	include	"Level/_Objects/Monitor and Time Post/Main.asm"
	include	"Level/_Objects/HUD and Points/Main.asm"
	include	"Level/_Objects/Level End/Main.asm"
	include	"Level/_Objects/Game Over/Main.asm"
	include	"Level/_Objects/Title Card/Main.asm"
	include	"Level/_Objects/Results/Main.asm"
	include	"Level/Wacky Workbench/Title Card Data.asm"
	include	"Level/Section Art Load (Null).asm"
	include	"Level/Object Tile ID Set (Null).asm"
	include	"Level/Wacky Workbench/Objects/Piston/Main.asm"
	include	"Level/Wacky Workbench/Objects/Electric Beams/Main.asm"
	include	"Level/Wacky Workbench/Objects/Platform/Main (Normal).asm"
	include	"Level/Wacky Workbench/Objects/Platform/Main (Bounce).asm"
	include	"Level/Wacky Workbench/Objects/Switch/Main.asm"
	include	"Level/Wacky Workbench/Objects/Door/Main.asm"
	include	"Level/Wacky Workbench/Objects/Tube Door/Main.asm"
	include	"Level/Wacky Workbench/Objects/Platform/Main (Spinning).asm"
	include	"Level/Wacky Workbench/Objects/Bata-pyon/Main.asm"
	include	"Level/Wacky Workbench/Objects/Poh-Bee/Main.asm"
	include	"Level/Wacky Workbench/Objects/Semi/Main.asm"
	include	"Level/Wacky Workbench/Objects/Minomusi/Main.asm"
	include	"Level/Wacky Workbench/Objects/Animal/Main.asm"
	include	"Level/Wacky Workbench/Objects/Snake Blocks/Main.asm"
	include	"Level/Wacky Workbench/Objects/Eggman Statue/Main.asm"
	include	"Level/Wacky Workbench/Objects/Seesaw/Main.asm"
	include	"Level/_Objects/Robot Generator/Main.asm"
	include	"Level/Wacky Workbench/Objects/Robot Generator/Tile IDs.asm"
	include	"Level/Wacky Workbench/Objects/Projector/Main.asm"
	include	"Level/Object Time Check.asm"
	include	"Level/Wacky Workbench/Animated Tiles Update (Act 1 Present).asm"
	include	"Level/Wacky Workbench/Data (Act 1 Present).asm"

; -------------------------------------------------------------------------
